# Generated by Django 6.0.5 on 2026-05-25 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['year', 'name'],
            },
        ),
    ]
